# Generated by Django 5.0.7 on 2024-08-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='is_subscribed',
            field=models.BooleanField(blank=True, verbose_name='Подписка на пользователя'),
        ),
    ]
