# Generated by Django 5.0.7 on 2024-09-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingre',
            field=models.ManyToManyField(to='recipes.ingredient', verbose_name='Ингре'),
        ),
    ]
