# Generated by Django 5.0.7 on 2024-10-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.FileField(max_length=32000, upload_to='recipes/', verbose_name='Изображение рецепта'),
        ),
    ]
