# Generated by Django 5.0.7 on 2024-08-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_apiuser_is_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='is_subscribed',
            field=models.BooleanField(default=False, verbose_name='Подписка на пользователя'),
        ),
    ]
